name: Build & deploy templates

env:
  dotnet_version: 5.0.100-rc.2.20479.15
  target_framework: netstandard2.0

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test package
      run: |
        dotnet new -i bin/Release/BlazorTemplates*.nupkg
        templates=$( dotnet new | grep "blazor-" | cut -c ${column_1_width}- | cut -d ' ' -f7 )
        echo "Testing templates ${templates}"
        while IFS=read -r template_name; do
           echo "Testing template ${template_name}"
           mkdir tmp
           cd tmp
           dotnet new ${template_name} --name TestInstance
           dotnet build
           cd ..
           rm -rf tmp
       done <<< "${templates}"