name: Build & deploy templates

env:
  dotnet_version: 5.0.100-rc.2.20479.15
  target_framework: netstandard2.0

on:
  push:
    branches: [ main ]

jobs:
  all:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore templates.csproj
    - name: Build
      run: dotnet build -c Release --no-restore templates.csproj
    - name: Test package
      run: |
        dotnet new -i bin/Release/BlazorTemplates*.nupkg
        column_1_width=$( dotnet new | grep -e "----" | cut -d ' ' -f1 | wc -c )
        templates=$( dotnet new | grep "blazor-" | cut -c ${column_1_width}- | cut -d ' ' -f7 )
        while IFS= read -r template_name; do
           echo "Testing template ${template_name}"
           mkdir tmp
           cd tmp
           dotnet new ${template_name} --name TestInstance
           dotnet build
           cd ..
           rm -rf tmp
        done <<< "${templates}"
    - name: Deploy
      run: |
        dotnet nuget push -s https://api.nuget.org/v3/index.json bin/Release/BlazorTemplates*.nupkg -k ${{ secrets.NUGETKEY }}