name: Build & deploy templates

env:
  dotnet_version: 5.0.200
  target_framework: netstandard2.0

on:
  push:
    branches: [ main ]

jobs:
  all:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore templates.csproj
    - name: Build
      run: dotnet build -c Release --no-restore templates.csproj
    - name: Pack
      run: dotnet pack -c Release -o app/packed --no-restore templates.csproj
    - name: Test package
      run: |
        dotnet new -i app/packed/*.nupkg
        column_1_width=$( dotnet new | grep -e "----" | cut -d ' ' -f1 | wc -c )
        templates=$( dotnet new | cut -c ${column_1_width}- | grep "blazor-"  | sed 's/^[ ]*//' | cut -d ' ' -f1 )
        while IFS= read -r template_name; do
           echo "Testing template ${template_name}"
           mkdir tmp
           cd tmp
           dotnet new ${template_name} --name TestInstance
           dotnet build
           cd ..
           rm -rf tmp
        done <<< "${templates}"
    - name: Deploy
      run: |
        dotnet nuget push -s https://api.nuget.org/v3/index.json app/packed/*.nupkg -k ${{ secrets.NUGETKEY }} > push_log || grep "409" push_log
